JENKINS-59301 possible solutions - Crowd 2 plugin not compatible with JDK11
jenkinsci/crowd2-plugin pull request #40
Opened 2021-09-19 18:48 UTC by Rifffi

implement a classloader hack between ever rest methode call. This is
only up for JAVA >= 11
see https://www.jenkins.io/doc/developer/plugin-development/dependencies-and-class-loading/

update some dependencies
added:
jaxb plugin 2.3.0.1
changed:
crowd rest client 4.0.2
apache-httpcomonents-client 4.5.13-1.0
commons-lang3 3.8

add minimum jenkins version to 2.163 because jaxb plugin need this

2021-09-19 18:58 UTC, Rifffi commented
Used the test case from https://github.com/jenkinsci/crowd2-plugin/pull/37.

2021-09-28 19:31 UTC, KalleOlaviNiemitalo commented
Is this hack compatible with <https://github.com/jenkinsci/jenkins/pull/5698>?

2021-09-30 14:49 UTC, Rifffi commented
We are currently using Jenkins version 2.312 and the bouncycastle API 2.23, and this crowd2 version. Maybe I will be able to update and test to more recent versions in the near future.

2021-10-13 13:42 UTC, Rifffi commented
The test was successful with Verison 2.316 and bouncycastle API 2.25. Another test with the option hudson.ClassicPluginStrategy.useAntClassLoader=false was also successful.

2021-11-11 12:27 UTC, mahernandezp commented
I've tested this PR in jenkins/jenkins:2.303.3 docker image (latest LTS). It works!.
Thank you

2021-11-18 06:27 UTC, ricksbrown commented
Looks like the maintainer has moved on. The plugin is "up for adoption": https://plugins.jenkins.io/crowd2/

2021-11-19 01:03 UTC, ricksbrown commented
This change does indeed work on 2.303.3.

Did not seem to work using [IBM's version of Java 11](https://developer.ibm.com/languages/java/semeru-runtimes/downloads) - Semeru. Could have been something else I did, but switched to OpenJDK and it works.

2021-12-02 19:26 UTC, preddymm commented
@mahernandezp Could you share what changes you have made to work on jenkins/jenkins:2.303.3. I tried the same way what it was shown in https://github.com/jenkinsci/crowd2-plugin/pull/40.

2021-12-02 20:52 UTC, Rifffi commented
Don't change anything on the pom.xml. Than run maven with the goals _clean install_
You can also try to disable checks and tests _clean install -Denforcer.fail=false -Dspotbugs.failOnError=false -DskipTests_

<jenkins.version>2.163</jenkins.version> stands for the most minimal version

2021-12-02 20:56 UTC, Rifffi commented
> This change does indeed work on 2.303.3.
> 
> Did not seem to work using [IBM's version of Java 11](https://developer.ibm.com/languages/java/semeru-runtimes/downloads) - Semeru. Could have been something else I did, but switched to OpenJDK and it works.

Could be a bug in the rest of the crowd library. The detection that it is java 11 works.

2021-12-02 20:58 UTC, Rifffi commented
> @mahernandezp Could you share what changes you have made to work on jenkins/jenkins:2.303.3. I tried the same way what it was shown in #40. It doesn't worked for me for 2.303.3.
> 
> When I do the mvn package by changing the Jenkins version, It is giving me the following error.
> 
> [WARNING] Rule 4: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message: Failed while enforcing RequireUpperBoundDeps. The error(s) are [ Require upper bound dependencies error for com.github.spotbugs:spotbugs-annotations:3.1.12 paths to dependency are: +-org.jenkins-ci.plugins:crowd2:2.0.3-SNAPSHOT +-com.github.spotbugs:spotbugs-annotations:3.1.12 and +-org.jenkins-ci.plugins:crowd2:2.0.3-SNAPSHOT +-org.jenkins-ci.main:jenkins-core:2.303.3 +-org.kohsuke.stapler:stapler:1563.v3da2d02f9572 +-com.github.spotbugs:spotbugs-annotations:3.1.12 (managed) <-- com.github.spotbugs:spotbugs-annotations:4.2.3 , Require upper bound dependencies error for org.slf4j:jcl-over-slf4j:1.7.25 paths to dependency are: +-org.jenkins-ci.plugins:crowd2:2.0.3-SNAPSHOT +-org.slf4j:jcl-over-slf4j:1.7.25 and +-org.jenkins-ci.plugins:crowd2:2.0.3-SNAPSHOT +-org.jenkins-ci.main:jenkins-core:2.303.3 +-org.slf4j:jcl-over-slf4j:1.7.31 , Require upper bound dependencies error for org.slf4j:log4j-over-slf4j:1.7.25 paths to dependency are: +-org.jenkins-ci.plugins:crowd2:2.0.3-SNAPSHOT +-org.slf4j:log4j-over-slf4j:1.7.25 and +-org.jenkins-ci.plugins:crowd2:2.0.3-SNAPSHOT +-org.jenkins-ci.main:jenkins-core:2.303.3 +-org.slf4j:log4j-over-slf4j:1.7.31 , Require upper bound dependencies error for org.kohsuke:access-modifier-annotation:1.16 paths to dependency are: +-org.jenkins-ci.plugins:crowd2:2.0.3-SNAPSHOT +-org.kohsuke:access-modifier-annotation:1.16 and +-org.jenkins-ci.plugins:crowd2:2.0.3-SNAPSHOT +-org.jenkins-ci.main:jenkins-core:2.303.3 +-org.kohsuke:access-modifier-annotation:1.21 , Require upper bound dependencies error for org.slf4j:slf4j-jdk14:1.7.25 paths to dependency are: +-org.jenkins-ci.plugins:crowd2:2.0.3-SNAPSHOT +-org.slf4j:slf4j-jdk14:1.7.25 and +-org.jenkins-ci.plugins:crowd2:2.0.3-SNAPSHOT +-org.jenkins-ci.main:jenkins-war:2.303.3 +-org.slf4j:slf4j-jdk14:1.7.31 ]

Don't change anything on the pom.xml. Than run maven with the goals _clean install_
You can also try to disable checks and tests _clean install -Denforcer.fail=false -Dspotbugs.failOnError=false -DskipTests_

<jenkins.version>2.163</jenkins.version> stands for the most minimal version

2021-12-03 07:32 UTC, irrationalism commented
FYI: We have it running on the newest jenkins lts version without any problems.

2021-12-06 16:26 UTC, preddymm commented
@Rifffi @mahernandezp @irrationalism 
It worked for me. Thank you so much!
I have a question on https://issues.jenkins.io/browse/JENKINS-64186
Any idea on this? I have to check disable remember me to work this.

Thanks

2021-12-14 23:39 UTC, preddymm commented
@Rifffi @irrationalism @mahernandezp @KalleOlaviNiemitalo @ricksbrown 

I have a question on https://issues.jenkins.io/browse/JENKINS-64186
Any idea on this? I have to check disable remember me to work this.

Please do let me know your ideas on this

2022-04-01 22:58 UTC, DuMaM requested changes

2022-04-01 22:58 UTC, DuMaM commented on pom.xml
> +        <crowd-integration-client-rest.version>4.0.2</crowd-integration-client-rest.version>
I would left current version of crowd for now. This change will only provide a JAVA11 compatibility.
Bumping rest client version would be a breaking change.

2022-04-01 22:58 UTC, DuMaM commented on pom.xml
> +        <crowd-integration-client-rest.version>4.0.2</crowd-integration-client-rest.version>
```suggestion
        <crowd-integration-client-rest.version>2.8.8</crowd-integration-client-rest.version>
```

2022-04-02 00:30 UTC, DuMaM commented
I need to add some changes required by org first.
https://github.com/jenkinsci/crowd2-plugin/pull/42
Then I will be able to integrate this PR.

2022-04-02 00:44 UTC, DuMaM approved these changes

2022-04-02 00:48 UTC, merged